name: CI

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Sync
        run: uv sync -v
